#
# Docker NodeJS
# Example Docker Compose file
#

# For more information about the directives defined here:
# https://docs.docker.com/compose/compose-file/

# Docker compose file version
version: "3.7"

services:
  app:
    build: .
    working_dir: /app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - .:/app/node_modules/bcrypt
    command: npm run watch
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DBNAME=test
      - POSTGRES_DBUSER=test
      - POSTGRES_DBPASS=test
    logging:
      options:
        max-size: 10m
        max-file: 3
    ports:
      - 5438:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE
