#
# Docker NodeJS
# Example Docker Compose file
#

# For more information about the directives defined here:
# https://docs.docker.com/compose/compose-file/

# Docker compose file version
version: "3.8"

services:
  app2:
    build: .
    working_dir: /app
    container_name: app_test
    env_file:
      - .env_test
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules/bcrypt
    command: npm run watch2
    depends_on:
      - postgres2
      - redis2

  redis2:
    image: redis:alpine
    container_name: redis_test
    ports:
      - ${HOST_PORT_REDIS}:${CONTAINER_PORT_REDIS}
    volumes:
      - ./redis-data:/data

  postgres2:
    container_name: postgres_test
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_DB=test_db_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_SCHEMA=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - SECRET=secret
    logging:
      options:
        max-size: 10m
        max-file: '10' # good
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE
volumes:
  postgres-data:
